# Generated by Django 5.0.6 on 2024-06-10 19:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0002_initial'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='productattribute',
            unique_together={('attribute_name', 'attribute_value')},
        ),
    ]
