# Generated by Django 5.0.6 on 2024-06-10 21:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0004_alter_productattribute_unique_together'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='productattribute',
            unique_together={('product', 'attribute_name', 'attribute_value')},
        ),
    ]
