# Generated by Django 5.0.6 on 2024-06-10 21:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0005_alter_productattribute_unique_together'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='productvariation',
            unique_together={('product', 'variation')},
        ),
    ]
