# Generated by Django 5.0.6 on 2024-06-14 11:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0007_alter_productattribute_product'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='productcolor',
            unique_together={('product', 'color')},
        ),
    ]
