# Generated by Django 5.0.6 on 2024-07-08 10:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0009_alter_review_unique_together'),
    ]

    operations = [
        migrations.RenameField(
            model_name='commentlikedislike',
            old_name='user',
            new_name='author',
        ),
    ]
